### ISSUE TITLE
Bug when handling constant strings with spaces

### ISSUE THREAD

**Issue by A-deLuna** [rattlesnake-pit/asm#28]
I was making this simple test: 

```
defs var, 12
pushks "HOLA MUNDO!"
pops var
prts var
prtcr
```

and encountered the error:

> EXPECTED '"'

the reason is that we're using next() to scan  the next token and next() always treats whitespace as the end of a token.

I think we should make another scanner function called nextString() and will stop when finding a " or \n

**Comment by jlvivero** [comment]
I'll grab this since it's related to what i've been working on

**Comment by jlvivero** [comment]
to be more specific I believe the problem lies in getName(); and isAlphaNum();
This is where it gets the string
`while(isAlphaNum(look))`

isAlphaNum() doesn't count spaces and that's why it has that problem

Here are the solutions that come to mind  

make a new function getStringName()
that instead of checking isAlphaNum() checks a new function isString() that includes everything except \0 and "
or i can just write the condition in the while directly what do you think @A-deLuna and @EduardoMY?

**Comment by A-deLuna** [comment]
I like the first option, after parsing the first " lets call that function.
Also getName should remain unchanged

**Comment by jlvivero** [comment]
it is done @A-deLuna  @EduardoMY  i will merge it if no one has a problem with it
